version: "3.3"

services:
  framework:
    image: rehive/tesserarius:0.0.0
    user: nobody
    env_file: $PWD/.env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    tty: true
